package com.novaguard.surveillance

import com.facebook.react.bridge.ReactApplicationContext

/**
 * JS entry point for {@link SurveillanceService}.
 *
 * `NativeSurveillanceServiceSpec` is generated by codegen from
 * `src/specs/NativeSurveillanceService.ts` (see `codegenConfig` in package.json).
 */
class SurveillanceServiceModule(reactContext: ReactApplicationContext) :
  NativeSurveillanceServiceSpec(reactContext) {

  override fun getName(): String = NAME

  override fun start(title: String, body: String) {
    // Android only allows a camera-type foreground service to be started while
    // the app is visible, which is the case here: monitoring is started by a tap.
    SurveillanceService.start(reactApplicationContext, title, body)
  }

  override fun stop() {
    SurveillanceService.stop(reactApplicationContext)
  }

  override fun isRunning(): Boolean = SurveillanceService.isRunning

  companion object {
    const val NAME = "SurveillanceService"
  }
}
