package com.novaguard.surveillance

import android.os.BatteryManager
import android.os.PowerManager
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import java.util.concurrent.Executors

/**
 * JS entry point for {@link SurveillanceService}.
 *
 * `NativeSurveillanceServiceSpec` is generated by codegen from
 * `src/specs/NativeSurveillanceService.ts` (see `codegenConfig` in package.json).
 */
class SurveillanceServiceModule(reactContext: ReactApplicationContext) :
  NativeSurveillanceServiceSpec(reactContext) {

  override fun getName(): String = NAME

  override fun start(title: String, body: String) {
    // Android only allows a camera-type foreground service to be started while
    // the app is visible, which is the case here: monitoring is started by a tap.
    SurveillanceService.start(reactApplicationContext, title, body)
  }

  override fun stop() {
    SurveillanceService.stop(reactApplicationContext)
  }

  override fun isRunning(): Boolean = SurveillanceService.isRunning

  override fun lastError(): String = SurveillanceService.lastError.orEmpty()

  override fun notifyDetection(title: String, body: String) {
    DetectionNotifier.notify(reactApplicationContext, title, body)
  }

  override fun dismissDetection() {
    DetectionNotifier.dismiss(reactApplicationContext)
  }

  override fun shareRecording(path: String): Boolean =
    ClipSharing.share(reactApplicationContext, path)

  override fun openDetectionChannelSettings() {
    DetectionNotifier.openChannelSettings(reactApplicationContext)
  }

  /**
   * What the platform says about heat and power.
   *
   * All three answer with "unknown" rather than throwing: the analysis loop
   * that reads them runs on every device, and a phone whose OEM does not
   * implement thermal reporting must degrade to the cadence measurement it
   * already had, not to a crash. `getSystemService` can return null on a
   * stripped image, which is the case the null-safe calls cover.
   */
  override fun thermalStatus(): Double {
    val power = reactApplicationContext.getSystemService(PowerManager::class.java)
    return power?.currentThermalStatus?.toDouble() ?: UNKNOWN
  }

  override fun batteryLevel(): Double {
    val battery = reactApplicationContext.getSystemService(BatteryManager::class.java)
    val level = battery?.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY) ?: -1
    // The property answers Integer.MIN_VALUE on a device that does not report
    // it, which is not a percentage and must not be shown as one.
    return if (level in 0..100) level.toDouble() else UNKNOWN
  }

  override fun isCharging(): Boolean {
    val battery = reactApplicationContext.getSystemService(BatteryManager::class.java)
    return battery?.isCharging ?: false
  }

  /**
   * Off the calling thread on purpose: this opens and parses the container to
   * decode one frame, and the JS thread it is called from is the one about to
   * file the event.
   *
   * Never rejects. A clip with no readable frame resolves to "", and the card
   * keeps the placeholder it already draws for a clip recorded screen-off.
   */
  override fun extractThumbnail(clipPath: String, promise: Promise) {
    thumbnails.execute { promise.resolve(ClipThumbnail.extract(clipPath)) }
  }

  companion object {
    const val NAME = "SurveillanceService"

    /** What every reading above answers when the platform will not. */
    private const val UNKNOWN = -1.0

    // One thread, shared: clips are filed one at a time, and a pool would only
    // let several decodes compete for memory on the phone doing the watching.
    private val thumbnails = Executors.newSingleThreadExecutor()
  }
}
